"""
core/models.py -- Shared data models for the entire system
"""
from __future__ import annotations
import time
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional
from enum import Enum


class Market(str, Enum):
    US_STOCK   = "US_STOCK"
    PENNY      = "PENNY"
    NASDAQ     = "NASDAQ"
    ETF        = "ETF"
    CRYPTO     = "CRYPTO"
    INTL       = "INTERNATIONAL"


class SignalType(str, Enum):
    STRONG_BUY  = "STRONG_BUY"
    BUY         = "BUY"
    HOLD        = "HOLD"
    SELL        = "SELL"
    STRONG_SELL = "STRONG_SELL"
    WATCH       = "WATCH"  # on radar, not actionable yet


class SignalReason(str, Enum):
    TECHNICAL    = "TECHNICAL"
    FUNDAMENTAL  = "FUNDAMENTAL"
    SENTIMENT    = "SENTIMENT"
    NEWS         = "NEWS"
    MOMENTUM     = "MOMENTUM"
    VOLUME_SPIKE = "VOLUME_SPIKE"
    BREAKOUT     = "BREAKOUT"
    MULTI_AGENT  = "MULTI_AGENT"


@dataclass
class Tick:
    """Raw price update for a single ticker"""
    symbol: str
    price: float
    volume: float
    bid: float = 0.0
    ask: float = 0.0
    change_pct: float = 0.0
    market: Market = Market.US_STOCK
    ts: float = field(default_factory=time.time)
    provider: str = "unknown"

    def to_dict(self) -> Dict:
        d = asdict(self)
        d["market"] = self.market.value
        return d


@dataclass
class TickerProfile:
    """Full enriched profile for a scanned ticker"""
    symbol: str
    name: str = ""
    market: Market = Market.US_STOCK
    price: float = 0.0
    volume_24h: float = 0.0
    avg_volume: float = 0.0
    volume_ratio: float = 0.0         # current/avg -- spike detection
    change_pct: float = 0.0
    change_5d: float = 0.0
    market_cap: float = 0.0
    sector: str = ""
    industry: str = ""
    pe_ratio: float = 0.0
    rsi: float = 0.0
    macd_signal: str = ""             # "bullish" | "bearish" | "neutral"
    bb_position: float = 0.0         # 0=lower band, 1=upper band
    vwap_vs_price: float = 0.0       # % above/below VWAP
    sentiment_score: float = 0.0     # -1 to +1
    news_count_24h: int = 0
    insider_activity: str = ""
    composite_score: float = 0.0      # 0-100 watchlist ranking score
    scan_ts: float = field(default_factory=time.time)
    provider_data: Dict = field(default_factory=dict)

    # T0 multi-timeframe pre-filter results (set by t0_filter before Tier-1 LLM)
    h4_aligned: Optional[bool] = None          # 4h trend direction matches daily bias
    h1_vwap_confirmed: Optional[bool] = None   # 1h close on correct side of VWAP
    volume_expanding: Optional[bool] = None    # last 3 hourly bars show rising volume
    t0_score: int = 0                          # count of passing checks (0-3)

    def to_dict(self) -> Dict:
        d = asdict(self)
        d["market"] = self.market.value
        return d


@dataclass
class Signal:
    """A buy/sell/watch signal generated by the signal engine or AI agents"""
    symbol: str
    signal_type: SignalType
    conviction: float             # 0.0 – 1.0
    price_at_signal: float
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    risk_reward: Optional[float] = None
    reason: SignalReason = SignalReason.TECHNICAL
    summary: str = ""
    details: str = ""
    tags: List[str] = field(default_factory=list)
    agent: str = "signal_engine"
    market: Market = Market.US_STOCK
    ts: float = field(default_factory=time.time)
    expires_ts: Optional[float] = None

    def to_dict(self) -> Dict:
        d = asdict(self)
        d["signal_type"] = self.signal_type.value
        d["reason"] = self.reason.value
        d["market"] = self.market.value
        return d


@dataclass
class AgentActivity:
    """Real-time log of what an AI agent is doing -- shown in the live viewer"""
    agent_id: str
    agent_type: str              # "technical" | "fundamental" | "news" | "risk" | "master"
    symbol: str
    action: str                  # "analyzing" | "tool_call" | "reasoning" | "signal_emitted"
    message: str
    tool_name: Optional[str] = None
    tool_input: Optional[Dict] = None
    tool_output: Optional[str] = None
    ts: float = field(default_factory=time.time)

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class WatchlistItem:
    profile: TickerProfile
    rank: int = 0
    added_ts: float = field(default_factory=time.time)
    signals: List[Signal] = field(default_factory=list)
    latest_signal: Optional[Signal] = None
    agent_coverage: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict:
        d = {
            "profile": self.profile.to_dict(),
            "rank": self.rank,
            "added_ts": self.added_ts,
            "signals": [s.to_dict() for s in self.signals[-5:]],
            "latest_signal": self.latest_signal.to_dict() if self.latest_signal else None,
            "agent_coverage": self.agent_coverage,
        }
        return d
